
INSERT INTO DS_DRONE (SN, MODEL, MAX_WEIGHT, BATTERY_LEVEL, STATE) VALUES ('AN12133K23', 'LIGHT_WEIGHT', 200, 50, 'LOADING');
INSERT INTO DS_DRONE (SN, MODEL, MAX_WEIGHT, BATTERY_LEVEL, STATE) VALUES ('AK65412V53', 'MIDDLE_WEIGHT', 500, 20, 'IDLE');
INSERT INTO DS_DRONE (SN, MODEL, MAX_WEIGHT, BATTERY_LEVEL, STATE) VALUES ('AK24544V10', 'MIDDLE_WEIGHT', 500, 20, 'LOADED');

INSERT INTO DS_MEDICATION(NAME, WEIGHT, CODE, IMAGE_URL, DRONE_ID) VALUES ('Naproxen', 100, 'B705', 'https://www.drugs.com/images/pills/fio/IPL01901/naproxen.JPG', 1);
INSERT INTO DS_MEDICATION(NAME, WEIGHT, CODE, IMAGE_URL, DRONE_ID) VALUES ('Alprazolam', 150, 'G32500', 'https://www.drugs.com/images/pills/nlm/597623720.jpg', 2);

